version: "3.7"

services:
  blog-service:
    build:
      context: ./Blog
      dockerfile: Dockerfile
    image: blog-app-image
    container_name: blog-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=super
      - DB_NAME=blog-service

  gateway-service:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    image: gateway-app-image
    container_name: gateway-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "8090:8090" # REST API exposed ovde
    depends_on:
      - blog-service
      - stakeholders-service

  stakeholders-service:
    build:
      context: ./Stakeholder/src # folder u kojem je .NET projekat
      dockerfile: Dockerfile
    image: stakeholders-app-image
    container_name: stakeholders-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      #- database
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=stakeholders-service;Username=postgres;Password=super

  database:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: blog-service # inicijalna baza, ali možeš praviti više
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  app-network:
