version: "3.7"

services:
  blog-service:
    build:
      context: ./Blog
      dockerfile: Dockerfile
    image: blog-app-image
    container_name: blog-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "9090:9090"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo:27017

  gateway-service:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    image: gateway-app-image
    container_name: gateway-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "8090:8090" # REST API exposed ovde
    depends_on:
      - blog-service
      - stakeholders-service
      - follower-service

  stakeholders-service:
    build:
      context: ./Stakeholder/src # folder u kojem je .NET projekat
      dockerfile: Dockerfile
    image: stakeholders-app-image
    container_name: stakeholders-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "8080:80"
      - "5000:5000"
    depends_on:
      #- database
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=stakeholders-service;Username=postgres;Password=super
    volumes:
      - ./Stakeholder/src/Explorer.API/wwwroot:/app/wwwroot


  tours-service:
    build:
      context: ./Tours
      dockerfile: Dockerfile
    image: tours-app-image
    container_name: tours-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "8081:90"
      - "5001:5000"
    depends_on:
      #- database
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:90;http://+:5000
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=tours-service;Username=postgres;Password=super
    volumes:
      - ./Tours/Tours.API/wwwroot:/app/wwwroot


      
  follower-service:
    build:
      context: ./Follower
      dockerfile: Dockerfile
    image: follower-app-image
    container_name: follower-app-container
    restart: always
    networks:
      - app-network
    ports:
      - "9091:9091"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=super1234


  database:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: blog-service # inicijalna baza, ali možeš praviti više
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    restart: always
    networks:
      - app-network
    ports:
      - "7474:7474"   # web interfejs
      - "7687:7687"   # bolt konekcija
    environment:
      - NEO4J_AUTH=neo4j/super1234  # username=neo4j, password=super1234
    volumes:
      - neo4j-data:/data

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - app-network


volumes:
  db-data:
  neo4j-data:

networks:
  app-network:
