// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: tours/tours.proto

package tours

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToursService_AddTour_FullMethodName                      = "/tours.ToursService/AddTour"
	ToursService_GetToursByUser_FullMethodName               = "/tours.ToursService/GetToursByUser"
	ToursService_GetTourById_FullMethodName                  = "/tours.ToursService/GetTourById"
	ToursService_AddTourDuration_FullMethodName              = "/tours.ToursService/AddTourDuration"
	ToursService_PublishTour_FullMethodName                  = "/tours.ToursService/PublishTour"
	ToursService_ArchiveTour_FullMethodName                  = "/tours.ToursService/ArchiveTour"
	ToursService_ReactivateTour_FullMethodName               = "/tours.ToursService/ReactivateTour"
	ToursService_GetPublishedToursForTourists_FullMethodName = "/tours.ToursService/GetPublishedToursForTourists"
	ToursService_GetAllTours_FullMethodName                  = "/tours.ToursService/GetAllTours"
)

// ToursServiceClient is the client API for ToursService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =================== Tours Service ===================
type ToursServiceClient interface {
	// Dodavanje ture
	AddTour(ctx context.Context, in *AddTourRequest, opts ...grpc.CallOption) (*Tour, error)
	GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetToursByUserResponse, error)
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*Tour, error)
	AddTourDuration(ctx context.Context, in *AddTourDurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PublishTour(ctx context.Context, in *PublishTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ArchiveTour(ctx context.Context, in *ArchiveTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReactivateTour(ctx context.Context, in *ReactivateTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPublishedToursForTourists(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPublishedToursForTouristsResponse, error)
	GetAllTours(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetToursByUserResponse, error)
}

type toursServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToursServiceClient(cc grpc.ClientConnInterface) ToursServiceClient {
	return &toursServiceClient{cc}
}

func (c *toursServiceClient) AddTour(ctx context.Context, in *AddTourRequest, opts ...grpc.CallOption) (*Tour, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tour)
	err := c.cc.Invoke(ctx, ToursService_AddTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetToursByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToursByUserResponse)
	err := c.cc.Invoke(ctx, ToursService_GetToursByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*Tour, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tour)
	err := c.cc.Invoke(ctx, ToursService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) AddTourDuration(ctx context.Context, in *AddTourDurationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ToursService_AddTourDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) PublishTour(ctx context.Context, in *PublishTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ToursService_PublishTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) ArchiveTour(ctx context.Context, in *ArchiveTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ToursService_ArchiveTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) ReactivateTour(ctx context.Context, in *ReactivateTourRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ToursService_ReactivateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetPublishedToursForTourists(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPublishedToursForTouristsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishedToursForTouristsResponse)
	err := c.cc.Invoke(ctx, ToursService_GetPublishedToursForTourists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetAllTours(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetToursByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToursByUserResponse)
	err := c.cc.Invoke(ctx, ToursService_GetAllTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToursServiceServer is the server API for ToursService service.
// All implementations must embed UnimplementedToursServiceServer
// for forward compatibility.
//
// =================== Tours Service ===================
type ToursServiceServer interface {
	// Dodavanje ture
	AddTour(context.Context, *AddTourRequest) (*Tour, error)
	GetToursByUser(context.Context, *GetToursByUserRequest) (*GetToursByUserResponse, error)
	GetTourById(context.Context, *GetTourByIdRequest) (*Tour, error)
	AddTourDuration(context.Context, *AddTourDurationRequest) (*emptypb.Empty, error)
	PublishTour(context.Context, *PublishTourRequest) (*emptypb.Empty, error)
	ArchiveTour(context.Context, *ArchiveTourRequest) (*emptypb.Empty, error)
	ReactivateTour(context.Context, *ReactivateTourRequest) (*emptypb.Empty, error)
	GetPublishedToursForTourists(context.Context, *emptypb.Empty) (*GetPublishedToursForTouristsResponse, error)
	GetAllTours(context.Context, *emptypb.Empty) (*GetToursByUserResponse, error)
	mustEmbedUnimplementedToursServiceServer()
}

// UnimplementedToursServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToursServiceServer struct{}

func (UnimplementedToursServiceServer) AddTour(context.Context, *AddTourRequest) (*Tour, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTour not implemented")
}
func (UnimplementedToursServiceServer) GetToursByUser(context.Context, *GetToursByUserRequest) (*GetToursByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToursByUser not implemented")
}
func (UnimplementedToursServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*Tour, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedToursServiceServer) AddTourDuration(context.Context, *AddTourDurationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTourDuration not implemented")
}
func (UnimplementedToursServiceServer) PublishTour(context.Context, *PublishTourRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishTour not implemented")
}
func (UnimplementedToursServiceServer) ArchiveTour(context.Context, *ArchiveTourRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveTour not implemented")
}
func (UnimplementedToursServiceServer) ReactivateTour(context.Context, *ReactivateTourRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReactivateTour not implemented")
}
func (UnimplementedToursServiceServer) GetPublishedToursForTourists(context.Context, *emptypb.Empty) (*GetPublishedToursForTouristsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedToursForTourists not implemented")
}
func (UnimplementedToursServiceServer) GetAllTours(context.Context, *emptypb.Empty) (*GetToursByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedToursServiceServer) mustEmbedUnimplementedToursServiceServer() {}
func (UnimplementedToursServiceServer) testEmbeddedByValue()                      {}

// UnsafeToursServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToursServiceServer will
// result in compilation errors.
type UnsafeToursServiceServer interface {
	mustEmbedUnimplementedToursServiceServer()
}

func RegisterToursServiceServer(s grpc.ServiceRegistrar, srv ToursServiceServer) {
	// If the following call pancis, it indicates UnimplementedToursServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToursService_ServiceDesc, srv)
}

func _ToursService_AddTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).AddTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_AddTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).AddTour(ctx, req.(*AddTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetToursByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetToursByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetToursByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetToursByUser(ctx, req.(*GetToursByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_AddTourDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTourDurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).AddTourDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_AddTourDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).AddTourDuration(ctx, req.(*AddTourDurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_PublishTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).PublishTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_PublishTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).PublishTour(ctx, req.(*PublishTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_ArchiveTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).ArchiveTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_ArchiveTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).ArchiveTour(ctx, req.(*ArchiveTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_ReactivateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactivateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).ReactivateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_ReactivateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).ReactivateTour(ctx, req.(*ReactivateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetPublishedToursForTourists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetPublishedToursForTourists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetPublishedToursForTourists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetPublishedToursForTourists(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetAllTours(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ToursService_ServiceDesc is the grpc.ServiceDesc for ToursService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToursService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.ToursService",
	HandlerType: (*ToursServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTour",
			Handler:    _ToursService_AddTour_Handler,
		},
		{
			MethodName: "GetToursByUser",
			Handler:    _ToursService_GetToursByUser_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _ToursService_GetTourById_Handler,
		},
		{
			MethodName: "AddTourDuration",
			Handler:    _ToursService_AddTourDuration_Handler,
		},
		{
			MethodName: "PublishTour",
			Handler:    _ToursService_PublishTour_Handler,
		},
		{
			MethodName: "ArchiveTour",
			Handler:    _ToursService_ArchiveTour_Handler,
		},
		{
			MethodName: "ReactivateTour",
			Handler:    _ToursService_ReactivateTour_Handler,
		},
		{
			MethodName: "GetPublishedToursForTourists",
			Handler:    _ToursService_GetPublishedToursForTourists_Handler,
		},
		{
			MethodName: "GetAllTours",
			Handler:    _ToursService_GetAllTours_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}

const (
	KeyPointService_AddKeyPoint_FullMethodName        = "/tours.KeyPointService/AddKeyPoint"
	KeyPointService_UpdateKeyPoint_FullMethodName     = "/tours.KeyPointService/UpdateKeyPoint"
	KeyPointService_DeleteKeyPoint_FullMethodName     = "/tours.KeyPointService/DeleteKeyPoint"
	KeyPointService_GetKeyPointsByUser_FullMethodName = "/tours.KeyPointService/GetKeyPointsByUser"
	KeyPointService_GetKeyPointById_FullMethodName    = "/tours.KeyPointService/GetKeyPointById"
	KeyPointService_GetKeyPointsByTour_FullMethodName = "/tours.KeyPointService/GetKeyPointsByTour"
)

// KeyPointServiceClient is the client API for KeyPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =================== KeyPoint Service ===================
type KeyPointServiceClient interface {
	AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPoint, error)
	UpdateKeyPoint(ctx context.Context, in *KeyPoint, opts ...grpc.CallOption) (*KeyPoint, error)
	DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error)
	GetKeyPointsByUser(ctx context.Context, in *GetKeyPointsByUserRequest, opts ...grpc.CallOption) (*GetKeyPointsByUserResponse, error)
	GetKeyPointById(ctx context.Context, in *GetKeyPointByIdRequest, opts ...grpc.CallOption) (*KeyPoint, error)
	GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error)
}

type keyPointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyPointServiceClient(cc grpc.ClientConnInterface) KeyPointServiceClient {
	return &keyPointServiceClient{cc}
}

func (c *keyPointServiceClient) AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_AddKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) UpdateKeyPoint(ctx context.Context, in *KeyPoint, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_UpdateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyPointResponse)
	err := c.cc.Invoke(ctx, KeyPointService_DeleteKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointsByUser(ctx context.Context, in *GetKeyPointsByUserRequest, opts ...grpc.CallOption) (*GetKeyPointsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsByUserResponse)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointById(ctx context.Context, in *GetKeyPointByIdRequest, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsByTourResponse)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointsByTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyPointServiceServer is the server API for KeyPointService service.
// All implementations must embed UnimplementedKeyPointServiceServer
// for forward compatibility.
//
// =================== KeyPoint Service ===================
type KeyPointServiceServer interface {
	AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPoint, error)
	UpdateKeyPoint(context.Context, *KeyPoint) (*KeyPoint, error)
	DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error)
	GetKeyPointsByUser(context.Context, *GetKeyPointsByUserRequest) (*GetKeyPointsByUserResponse, error)
	GetKeyPointById(context.Context, *GetKeyPointByIdRequest) (*KeyPoint, error)
	GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error)
	mustEmbedUnimplementedKeyPointServiceServer()
}

// UnimplementedKeyPointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyPointServiceServer struct{}

func (UnimplementedKeyPointServiceServer) AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) UpdateKeyPoint(context.Context, *KeyPoint) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointsByUser(context.Context, *GetKeyPointsByUserRequest) (*GetKeyPointsByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsByUser not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointById(context.Context, *GetKeyPointByIdRequest) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointById not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsByTour not implemented")
}
func (UnimplementedKeyPointServiceServer) mustEmbedUnimplementedKeyPointServiceServer() {}
func (UnimplementedKeyPointServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyPointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyPointServiceServer will
// result in compilation errors.
type UnsafeKeyPointServiceServer interface {
	mustEmbedUnimplementedKeyPointServiceServer()
}

func RegisterKeyPointServiceServer(s grpc.ServiceRegistrar, srv KeyPointServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyPointService_ServiceDesc, srv)
}

func _KeyPointService_AddKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).AddKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_AddKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).AddKeyPoint(ctx, req.(*AddKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_UpdateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).UpdateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_UpdateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).UpdateKeyPoint(ctx, req.(*KeyPoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_DeleteKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).DeleteKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_DeleteKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).DeleteKeyPoint(ctx, req.(*DeleteKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointsByUser(ctx, req.(*GetKeyPointsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointById(ctx, req.(*GetKeyPointByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointsByTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsByTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointsByTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointsByTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointsByTour(ctx, req.(*GetKeyPointsByTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyPointService_ServiceDesc is the grpc.ServiceDesc for KeyPointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyPointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.KeyPointService",
	HandlerType: (*KeyPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddKeyPoint",
			Handler:    _KeyPointService_AddKeyPoint_Handler,
		},
		{
			MethodName: "UpdateKeyPoint",
			Handler:    _KeyPointService_UpdateKeyPoint_Handler,
		},
		{
			MethodName: "DeleteKeyPoint",
			Handler:    _KeyPointService_DeleteKeyPoint_Handler,
		},
		{
			MethodName: "GetKeyPointsByUser",
			Handler:    _KeyPointService_GetKeyPointsByUser_Handler,
		},
		{
			MethodName: "GetKeyPointById",
			Handler:    _KeyPointService_GetKeyPointById_Handler,
		},
		{
			MethodName: "GetKeyPointsByTour",
			Handler:    _KeyPointService_GetKeyPointsByTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}

const (
	TourReviewService_AddTourReview_FullMethodName    = "/tours.TourReviewService/AddTourReview"
	TourReviewService_GetReviewsByTour_FullMethodName = "/tours.TourReviewService/GetReviewsByTour"
)

// TourReviewServiceClient is the client API for TourReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourReviewServiceClient interface {
	AddTourReview(ctx context.Context, in *AddTourReviewRequest, opts ...grpc.CallOption) (*TourReview, error)
	GetReviewsByTour(ctx context.Context, in *GetReviewsByTourRequest, opts ...grpc.CallOption) (*GetReviewsByTourResponse, error)
}

type tourReviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourReviewServiceClient(cc grpc.ClientConnInterface) TourReviewServiceClient {
	return &tourReviewServiceClient{cc}
}

func (c *tourReviewServiceClient) AddTourReview(ctx context.Context, in *AddTourReviewRequest, opts ...grpc.CallOption) (*TourReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourReview)
	err := c.cc.Invoke(ctx, TourReviewService_AddTourReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourReviewServiceClient) GetReviewsByTour(ctx context.Context, in *GetReviewsByTourRequest, opts ...grpc.CallOption) (*GetReviewsByTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewsByTourResponse)
	err := c.cc.Invoke(ctx, TourReviewService_GetReviewsByTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourReviewServiceServer is the server API for TourReviewService service.
// All implementations must embed UnimplementedTourReviewServiceServer
// for forward compatibility.
type TourReviewServiceServer interface {
	AddTourReview(context.Context, *AddTourReviewRequest) (*TourReview, error)
	GetReviewsByTour(context.Context, *GetReviewsByTourRequest) (*GetReviewsByTourResponse, error)
	mustEmbedUnimplementedTourReviewServiceServer()
}

// UnimplementedTourReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourReviewServiceServer struct{}

func (UnimplementedTourReviewServiceServer) AddTourReview(context.Context, *AddTourReviewRequest) (*TourReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTourReview not implemented")
}
func (UnimplementedTourReviewServiceServer) GetReviewsByTour(context.Context, *GetReviewsByTourRequest) (*GetReviewsByTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewsByTour not implemented")
}
func (UnimplementedTourReviewServiceServer) mustEmbedUnimplementedTourReviewServiceServer() {}
func (UnimplementedTourReviewServiceServer) testEmbeddedByValue()                           {}

// UnsafeTourReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourReviewServiceServer will
// result in compilation errors.
type UnsafeTourReviewServiceServer interface {
	mustEmbedUnimplementedTourReviewServiceServer()
}

func RegisterTourReviewServiceServer(s grpc.ServiceRegistrar, srv TourReviewServiceServer) {
	// If the following call pancis, it indicates UnimplementedTourReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourReviewService_ServiceDesc, srv)
}

func _TourReviewService_AddTourReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTourReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourReviewServiceServer).AddTourReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourReviewService_AddTourReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourReviewServiceServer).AddTourReview(ctx, req.(*AddTourReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourReviewService_GetReviewsByTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewsByTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourReviewServiceServer).GetReviewsByTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourReviewService_GetReviewsByTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourReviewServiceServer).GetReviewsByTour(ctx, req.(*GetReviewsByTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourReviewService_ServiceDesc is the grpc.ServiceDesc for TourReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.TourReviewService",
	HandlerType: (*TourReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTourReview",
			Handler:    _TourReviewService_AddTourReview_Handler,
		},
		{
			MethodName: "GetReviewsByTour",
			Handler:    _TourReviewService_GetReviewsByTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}

const (
	PositionSimulatorService_GetPosition_FullMethodName    = "/tours.PositionSimulatorService/GetPosition"
	PositionSimulatorService_UpdatePosition_FullMethodName = "/tours.PositionSimulatorService/UpdatePosition"
)

// PositionSimulatorServiceClient is the client API for PositionSimulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PositionSimulatorServiceClient interface {
	// GET metoda za preuzimanje trenutne pozicije turiste
	GetPosition(ctx context.Context, in *PositionSimulatorRequest, opts ...grpc.CallOption) (*PositionSimulatorResponse, error)
	// POST metoda za ažuriranje pozicije turiste
	UpdatePosition(ctx context.Context, in *UpdatePositionRequest, opts ...grpc.CallOption) (*PositionSimulatorResponse, error)
}

type positionSimulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionSimulatorServiceClient(cc grpc.ClientConnInterface) PositionSimulatorServiceClient {
	return &positionSimulatorServiceClient{cc}
}

func (c *positionSimulatorServiceClient) GetPosition(ctx context.Context, in *PositionSimulatorRequest, opts ...grpc.CallOption) (*PositionSimulatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionSimulatorResponse)
	err := c.cc.Invoke(ctx, PositionSimulatorService_GetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionSimulatorServiceClient) UpdatePosition(ctx context.Context, in *UpdatePositionRequest, opts ...grpc.CallOption) (*PositionSimulatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionSimulatorResponse)
	err := c.cc.Invoke(ctx, PositionSimulatorService_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionSimulatorServiceServer is the server API for PositionSimulatorService service.
// All implementations must embed UnimplementedPositionSimulatorServiceServer
// for forward compatibility.
type PositionSimulatorServiceServer interface {
	// GET metoda za preuzimanje trenutne pozicije turiste
	GetPosition(context.Context, *PositionSimulatorRequest) (*PositionSimulatorResponse, error)
	// POST metoda za ažuriranje pozicije turiste
	UpdatePosition(context.Context, *UpdatePositionRequest) (*PositionSimulatorResponse, error)
	mustEmbedUnimplementedPositionSimulatorServiceServer()
}

// UnimplementedPositionSimulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPositionSimulatorServiceServer struct{}

func (UnimplementedPositionSimulatorServiceServer) GetPosition(context.Context, *PositionSimulatorRequest) (*PositionSimulatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedPositionSimulatorServiceServer) UpdatePosition(context.Context, *UpdatePositionRequest) (*PositionSimulatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedPositionSimulatorServiceServer) mustEmbedUnimplementedPositionSimulatorServiceServer() {
}
func (UnimplementedPositionSimulatorServiceServer) testEmbeddedByValue() {}

// UnsafePositionSimulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionSimulatorServiceServer will
// result in compilation errors.
type UnsafePositionSimulatorServiceServer interface {
	mustEmbedUnimplementedPositionSimulatorServiceServer()
}

func RegisterPositionSimulatorServiceServer(s grpc.ServiceRegistrar, srv PositionSimulatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedPositionSimulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PositionSimulatorService_ServiceDesc, srv)
}

func _PositionSimulatorService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionSimulatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionSimulatorServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionSimulatorService_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionSimulatorServiceServer).GetPosition(ctx, req.(*PositionSimulatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionSimulatorService_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionSimulatorServiceServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionSimulatorService_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionSimulatorServiceServer).UpdatePosition(ctx, req.(*UpdatePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PositionSimulatorService_ServiceDesc is the grpc.ServiceDesc for PositionSimulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PositionSimulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.PositionSimulatorService",
	HandlerType: (*PositionSimulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPosition",
			Handler:    _PositionSimulatorService_GetPosition_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _PositionSimulatorService_UpdatePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}
