// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tours/tours.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	UserId        int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	LengthInKm    float64                `protobuf:"fixed64,9,opt,name=lengthInKm,proto3" json:"lengthInKm,omitempty"`
	PublishedTime string                 `protobuf:"bytes,10,opt,name=publishedTime,proto3" json:"publishedTime,omitempty"`
	ArchiveTime   string                 `protobuf:"bytes,11,opt,name=archiveTime,proto3" json:"archiveTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Tour) GetLengthInKm() float64 {
	if x != nil {
		return x.LengthInKm
	}
	return 0
}

func (x *Tour) GetPublishedTime() string {
	if x != nil {
		return x.PublishedTime
	}
	return ""
}

func (x *Tour) GetArchiveTime() string {
	if x != nil {
		return x.ArchiveTime
	}
	return ""
}

type AddTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	LengthInKm    float64                `protobuf:"fixed64,8,opt,name=lengthInKm,proto3" json:"lengthInKm,omitempty"`
	PublishedTime string                 `protobuf:"bytes,9,opt,name=publishedTime,proto3" json:"publishedTime,omitempty"`
	ArchiveTime   string                 `protobuf:"bytes,10,opt,name=archiveTime,proto3" json:"archiveTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTourRequest) Reset() {
	*x = AddTourRequest{}
	mi := &file_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTourRequest) ProtoMessage() {}

func (x *AddTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTourRequest.ProtoReflect.Descriptor instead.
func (*AddTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *AddTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *AddTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddTourRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddTourRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddTourRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddTourRequest) GetLengthInKm() float64 {
	if x != nil {
		return x.LengthInKm
	}
	return 0
}

func (x *AddTourRequest) GetPublishedTime() string {
	if x != nil {
		return x.PublishedTime
	}
	return ""
}

func (x *AddTourRequest) GetArchiveTime() string {
	if x != nil {
		return x.ArchiveTime
	}
	return ""
}

type GetToursByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByUserRequest) Reset() {
	*x = GetToursByUserRequest{}
	mi := &file_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByUserRequest) ProtoMessage() {}

func (x *GetToursByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByUserRequest.ProtoReflect.Descriptor instead.
func (*GetToursByUserRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *GetToursByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetToursByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByUserResponse) Reset() {
	*x = GetToursByUserResponse{}
	mi := &file_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByUserResponse) ProtoMessage() {}

func (x *GetToursByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByUserResponse.ProtoReflect.Descriptor instead.
func (*GetToursByUserResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *GetToursByUserResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,7,opt,name=imageBase64,proto3" json:"imageBase64,omitempty"`
	TourId        int64                  `protobuf:"varint,8,opt,name=tourId,proto3" json:"tourId,omitempty"`
	PublicStatus  int32                  `protobuf:"varint,9,opt,name=publicStatus,proto3" json:"publicStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_tours_tours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{4}
}

func (x *KeyPoint) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *KeyPoint) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *KeyPoint) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *KeyPoint) GetPublicStatus() int32 {
	if x != nil {
		return x.PublicStatus
	}
	return 0
}

type AddKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,5,opt,name=imageBase64,proto3" json:"imageBase64,omitempty"`
	TourId        int64                  `protobuf:"varint,6,opt,name=tourId,proto3" json:"tourId,omitempty"`
	PublicStatus  int32                  `protobuf:"varint,7,opt,name=publicStatus,proto3" json:"publicStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyPointRequest) Reset() {
	*x = AddKeyPointRequest{}
	mi := &file_tours_tours_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyPointRequest) ProtoMessage() {}

func (x *AddKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyPointRequest.ProtoReflect.Descriptor instead.
func (*AddKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{5}
}

func (x *AddKeyPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddKeyPointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddKeyPointRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *AddKeyPointRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *AddKeyPointRequest) GetPublicStatus() int32 {
	if x != nil {
		return x.PublicStatus
	}
	return 0
}

type DeleteKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointRequest) Reset() {
	*x = DeleteKeyPointRequest{}
	mi := &file_tours_tours_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointRequest) ProtoMessage() {}

func (x *DeleteKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKeyPointRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointResponse) Reset() {
	*x = DeleteKeyPointResponse{}
	mi := &file_tours_tours_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointResponse) ProtoMessage() {}

func (x *DeleteKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKeyPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetKeyPointsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByUserRequest) Reset() {
	*x = GetKeyPointsByUserRequest{}
	mi := &file_tours_tours_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByUserRequest) ProtoMessage() {}

func (x *GetKeyPointsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByUserRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{8}
}

func (x *GetKeyPointsByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetKeyPointsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,1,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByUserResponse) Reset() {
	*x = GetKeyPointsByUserResponse{}
	mi := &file_tours_tours_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByUserResponse) ProtoMessage() {}

func (x *GetKeyPointsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByUserResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeyPointsByUserResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type GetKeyPointByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointByIdRequest) Reset() {
	*x = GetKeyPointByIdRequest{}
	mi := &file_tours_tours_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointByIdRequest) ProtoMessage() {}

func (x *GetKeyPointByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointByIdRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointByIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeyPointByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_tours_tours_proto protoreflect.FileDescriptor

const file_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x11tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\"\xae\x02\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"lengthInKm\x18\t \x01(\x01R\n" +
	"lengthInKm\x12$\n" +
	"\rpublishedTime\x18\n" +
	" \x01(\tR\rpublishedTime\x12 \n" +
	"\varchiveTime\x18\v \x01(\tR\varchiveTime\"\xa8\x02\n" +
	"\x0eAddTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06userId\x18\a \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"lengthInKm\x18\b \x01(\x01R\n" +
	"lengthInKm\x12$\n" +
	"\rpublishedTime\x18\t \x01(\tR\rpublishedTime\x12 \n" +
	"\varchiveTime\x18\n" +
	" \x01(\tR\varchiveTime\"/\n" +
	"\x15GetToursByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x16GetToursByUserResponse\x12!\n" +
	"\x05tours\x18\x01 \x03(\v2\v.tours.TourR\x05tours\"\xfe\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12 \n" +
	"\vimageBase64\x18\a \x01(\tR\vimageBase64\x12\x16\n" +
	"\x06tourId\x18\b \x01(\x03R\x06tourId\x12\"\n" +
	"\fpublicStatus\x18\t \x01(\x05R\fpublicStatus\"\xe2\x01\n" +
	"\x12AddKeyPointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vimageBase64\x18\x05 \x01(\tR\vimageBase64\x12\x16\n" +
	"\x06tourId\x18\x06 \x01(\x03R\x06tourId\x12\"\n" +
	"\fpublicStatus\x18\a \x01(\x05R\fpublicStatus\"'\n" +
	"\x15DeleteKeyPointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16DeleteKeyPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x19GetKeyPointsByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x1aGetKeyPointsByUserResponse\x12-\n" +
	"\tkeyPoints\x18\x01 \x03(\v2\x0f.tours.KeyPointR\tkeyPoints\"(\n" +
	"\x16GetKeyPointByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xc5\x01\n" +
	"\fToursService\x12D\n" +
	"\aAddTour\x12\x15.tours.AddTourRequest\x1a\v.tours.Tour\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/tours\x12o\n" +
	"\x0eGetToursByUser\x12\x1c.tours.GetToursByUserRequest\x1a\x1d.tours.GetToursByUserResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/tours/user/{userId}2\x88\x04\n" +
	"\x0fKeyPointService\x12T\n" +
	"\vAddKeyPoint\x12\x19.tours.AddKeyPointRequest\x1a\x0f.tours.KeyPoint\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/keypoints\x12R\n" +
	"\x0eUpdateKeyPoint\x12\x0f.tours.KeyPoint\x1a\x0f.tours.KeyPoint\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/keypoints/{id}\x12j\n" +
	"\x0eDeleteKeyPoint\x12\x1c.tours.DeleteKeyPointRequest\x1a\x1d.tours.DeleteKeyPointResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/keypoints/{id}\x12\x7f\n" +
	"\x12GetKeyPointsByUser\x12 .tours.GetKeyPointsByUserRequest\x1a!.tours.GetKeyPointsByUserResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/keypoints/user/{userId}\x12^\n" +
	"\x0fGetKeyPointById\x12\x1d.tours.GetKeyPointByIdRequest\x1a\x0f.tours.KeyPoint\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/keypoints/{id}B&Z\vproto/tours\xaa\x02\x16GrpcServiceTranscodingb\x06proto3"

var (
	file_tours_tours_proto_rawDescOnce sync.Once
	file_tours_tours_proto_rawDescData []byte
)

func file_tours_tours_proto_rawDescGZIP() []byte {
	file_tours_tours_proto_rawDescOnce.Do(func() {
		file_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)))
	})
	return file_tours_tours_proto_rawDescData
}

var file_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tours_tours_proto_goTypes = []any{
	(*Tour)(nil),                       // 0: tours.Tour
	(*AddTourRequest)(nil),             // 1: tours.AddTourRequest
	(*GetToursByUserRequest)(nil),      // 2: tours.GetToursByUserRequest
	(*GetToursByUserResponse)(nil),     // 3: tours.GetToursByUserResponse
	(*KeyPoint)(nil),                   // 4: tours.KeyPoint
	(*AddKeyPointRequest)(nil),         // 5: tours.AddKeyPointRequest
	(*DeleteKeyPointRequest)(nil),      // 6: tours.DeleteKeyPointRequest
	(*DeleteKeyPointResponse)(nil),     // 7: tours.DeleteKeyPointResponse
	(*GetKeyPointsByUserRequest)(nil),  // 8: tours.GetKeyPointsByUserRequest
	(*GetKeyPointsByUserResponse)(nil), // 9: tours.GetKeyPointsByUserResponse
	(*GetKeyPointByIdRequest)(nil),     // 10: tours.GetKeyPointByIdRequest
}
var file_tours_tours_proto_depIdxs = []int32{
	0,  // 0: tours.GetToursByUserResponse.tours:type_name -> tours.Tour
	4,  // 1: tours.GetKeyPointsByUserResponse.keyPoints:type_name -> tours.KeyPoint
	1,  // 2: tours.ToursService.AddTour:input_type -> tours.AddTourRequest
	2,  // 3: tours.ToursService.GetToursByUser:input_type -> tours.GetToursByUserRequest
	5,  // 4: tours.KeyPointService.AddKeyPoint:input_type -> tours.AddKeyPointRequest
	4,  // 5: tours.KeyPointService.UpdateKeyPoint:input_type -> tours.KeyPoint
	6,  // 6: tours.KeyPointService.DeleteKeyPoint:input_type -> tours.DeleteKeyPointRequest
	8,  // 7: tours.KeyPointService.GetKeyPointsByUser:input_type -> tours.GetKeyPointsByUserRequest
	10, // 8: tours.KeyPointService.GetKeyPointById:input_type -> tours.GetKeyPointByIdRequest
	0,  // 9: tours.ToursService.AddTour:output_type -> tours.Tour
	3,  // 10: tours.ToursService.GetToursByUser:output_type -> tours.GetToursByUserResponse
	4,  // 11: tours.KeyPointService.AddKeyPoint:output_type -> tours.KeyPoint
	4,  // 12: tours.KeyPointService.UpdateKeyPoint:output_type -> tours.KeyPoint
	7,  // 13: tours.KeyPointService.DeleteKeyPoint:output_type -> tours.DeleteKeyPointResponse
	9,  // 14: tours.KeyPointService.GetKeyPointsByUser:output_type -> tours.GetKeyPointsByUserResponse
	4,  // 15: tours.KeyPointService.GetKeyPointById:output_type -> tours.KeyPoint
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tours_tours_proto_init() }
func file_tours_tours_proto_init() {
	if File_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tours_tours_proto_goTypes,
		DependencyIndexes: file_tours_tours_proto_depIdxs,
		MessageInfos:      file_tours_tours_proto_msgTypes,
	}.Build()
	File_tours_tours_proto = out.File
	file_tours_tours_proto_goTypes = nil
	file_tours_tours_proto_depIdxs = nil
}
