// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tours/tours.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tour
type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	UserId        int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	LengthInKm    float64                `protobuf:"fixed64,9,opt,name=lengthInKm,proto3" json:"lengthInKm,omitempty"`
	PublishedTime string                 `protobuf:"bytes,10,opt,name=publishedTime,proto3" json:"publishedTime,omitempty"`
	ArchiveTime   string                 `protobuf:"bytes,11,opt,name=archiveTime,proto3" json:"archiveTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Tour) GetLengthInKm() float64 {
	if x != nil {
		return x.LengthInKm
	}
	return 0
}

func (x *Tour) GetPublishedTime() string {
	if x != nil {
		return x.PublishedTime
	}
	return ""
}

func (x *Tour) GetArchiveTime() string {
	if x != nil {
		return x.ArchiveTime
	}
	return ""
}

type AddTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	LengthInKm    float64                `protobuf:"fixed64,8,opt,name=lengthInKm,proto3" json:"lengthInKm,omitempty"`
	PublishedTime string                 `protobuf:"bytes,9,opt,name=publishedTime,proto3" json:"publishedTime,omitempty"`
	ArchiveTime   string                 `protobuf:"bytes,10,opt,name=archiveTime,proto3" json:"archiveTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTourRequest) Reset() {
	*x = AddTourRequest{}
	mi := &file_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTourRequest) ProtoMessage() {}

func (x *AddTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTourRequest.ProtoReflect.Descriptor instead.
func (*AddTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *AddTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *AddTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddTourRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddTourRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddTourRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddTourRequest) GetLengthInKm() float64 {
	if x != nil {
		return x.LengthInKm
	}
	return 0
}

func (x *AddTourRequest) GetPublishedTime() string {
	if x != nil {
		return x.PublishedTime
	}
	return ""
}

func (x *AddTourRequest) GetArchiveTime() string {
	if x != nil {
		return x.ArchiveTime
	}
	return ""
}

type GetToursByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByUserRequest) Reset() {
	*x = GetToursByUserRequest{}
	mi := &file_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByUserRequest) ProtoMessage() {}

func (x *GetToursByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByUserRequest.ProtoReflect.Descriptor instead.
func (*GetToursByUserRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *GetToursByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetToursByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByUserResponse) Reset() {
	*x = GetToursByUserResponse{}
	mi := &file_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByUserResponse) ProtoMessage() {}

func (x *GetToursByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByUserResponse.ProtoReflect.Descriptor instead.
func (*GetToursByUserResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *GetToursByUserResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

// KeyPoint
type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,7,opt,name=imageBase64,proto3" json:"imageBase64,omitempty"`
	TourId        int64                  `protobuf:"varint,8,opt,name=tourId,proto3" json:"tourId,omitempty"`
	PublicStatus  int32                  `protobuf:"varint,9,opt,name=publicStatus,proto3" json:"publicStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_tours_tours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{4}
}

func (x *KeyPoint) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *KeyPoint) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *KeyPoint) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *KeyPoint) GetPublicStatus() int32 {
	if x != nil {
		return x.PublicStatus
	}
	return 0
}

type AddKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,5,opt,name=imageBase64,proto3" json:"imageBase64,omitempty"`
	TourId        int64                  `protobuf:"varint,6,opt,name=tourId,proto3" json:"tourId,omitempty"`
	PublicStatus  int32                  `protobuf:"varint,7,opt,name=publicStatus,proto3" json:"publicStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyPointRequest) Reset() {
	*x = AddKeyPointRequest{}
	mi := &file_tours_tours_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyPointRequest) ProtoMessage() {}

func (x *AddKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyPointRequest.ProtoReflect.Descriptor instead.
func (*AddKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{5}
}

func (x *AddKeyPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddKeyPointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AddKeyPointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddKeyPointRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *AddKeyPointRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *AddKeyPointRequest) GetPublicStatus() int32 {
	if x != nil {
		return x.PublicStatus
	}
	return 0
}

type DeleteKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointRequest) Reset() {
	*x = DeleteKeyPointRequest{}
	mi := &file_tours_tours_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointRequest) ProtoMessage() {}

func (x *DeleteKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKeyPointRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointResponse) Reset() {
	*x = DeleteKeyPointResponse{}
	mi := &file_tours_tours_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointResponse) ProtoMessage() {}

func (x *DeleteKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKeyPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetKeyPointsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByUserRequest) Reset() {
	*x = GetKeyPointsByUserRequest{}
	mi := &file_tours_tours_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByUserRequest) ProtoMessage() {}

func (x *GetKeyPointsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByUserRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{8}
}

func (x *GetKeyPointsByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetKeyPointsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,1,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByUserResponse) Reset() {
	*x = GetKeyPointsByUserResponse{}
	mi := &file_tours_tours_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByUserResponse) ProtoMessage() {}

func (x *GetKeyPointsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByUserResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeyPointsByUserResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type GetKeyPointByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointByIdRequest) Reset() {
	*x = GetKeyPointByIdRequest{}
	mi := &file_tours_tours_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointByIdRequest) ProtoMessage() {}

func (x *GetKeyPointByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointByIdRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointByIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeyPointByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddTourReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTour        int64                  `protobuf:"varint,1,opt,name=idTour,proto3" json:"idTour,omitempty"`
	IdTourist     int64                  `protobuf:"varint,2,opt,name=idTourist,proto3" json:"idTourist,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	DateTour      string                 `protobuf:"bytes,5,opt,name=dateTour,proto3" json:"dateTour,omitempty"`
	DateComment   string                 `protobuf:"bytes,6,opt,name=dateComment,proto3" json:"dateComment,omitempty"`
	ImagesBase64  []string               `protobuf:"bytes,7,rep,name=imagesBase64,proto3" json:"imagesBase64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTourReviewRequest) Reset() {
	*x = AddTourReviewRequest{}
	mi := &file_tours_tours_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTourReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTourReviewRequest) ProtoMessage() {}

func (x *AddTourReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTourReviewRequest.ProtoReflect.Descriptor instead.
func (*AddTourReviewRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{11}
}

func (x *AddTourReviewRequest) GetIdTour() int64 {
	if x != nil {
		return x.IdTour
	}
	return 0
}

func (x *AddTourReviewRequest) GetIdTourist() int64 {
	if x != nil {
		return x.IdTourist
	}
	return 0
}

func (x *AddTourReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddTourReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AddTourReviewRequest) GetDateTour() string {
	if x != nil {
		return x.DateTour
	}
	return ""
}

func (x *AddTourReviewRequest) GetDateComment() string {
	if x != nil {
		return x.DateComment
	}
	return ""
}

func (x *AddTourReviewRequest) GetImagesBase64() []string {
	if x != nil {
		return x.ImagesBase64
	}
	return nil
}

type TourReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdTour        int64                  `protobuf:"varint,2,opt,name=idTour,proto3" json:"idTour,omitempty"`
	IdTourist     int64                  `protobuf:"varint,3,opt,name=idTourist,proto3" json:"idTourist,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	DateTour      string                 `protobuf:"bytes,6,opt,name=dateTour,proto3" json:"dateTour,omitempty"`
	DateComment   string                 `protobuf:"bytes,7,opt,name=dateComment,proto3" json:"dateComment,omitempty"`
	Images        []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourReview) Reset() {
	*x = TourReview{}
	mi := &file_tours_tours_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourReview) ProtoMessage() {}

func (x *TourReview) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourReview.ProtoReflect.Descriptor instead.
func (*TourReview) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{12}
}

func (x *TourReview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourReview) GetIdTour() int64 {
	if x != nil {
		return x.IdTour
	}
	return 0
}

func (x *TourReview) GetIdTourist() int64 {
	if x != nil {
		return x.IdTourist
	}
	return 0
}

func (x *TourReview) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *TourReview) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *TourReview) GetDateTour() string {
	if x != nil {
		return x.DateTour
	}
	return ""
}

func (x *TourReview) GetDateComment() string {
	if x != nil {
		return x.DateComment
	}
	return ""
}

func (x *TourReview) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type GetKeyPointsByTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int64                  `protobuf:"varint,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByTourRequest) Reset() {
	*x = GetKeyPointsByTourRequest{}
	mi := &file_tours_tours_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByTourRequest) ProtoMessage() {}

func (x *GetKeyPointsByTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByTourRequest.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{13}
}

func (x *GetKeyPointsByTourRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

type GetKeyPointsByTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,1,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPointsByTourResponse) Reset() {
	*x = GetKeyPointsByTourResponse{}
	mi := &file_tours_tours_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPointsByTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPointsByTourResponse) ProtoMessage() {}

func (x *GetKeyPointsByTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPointsByTourResponse.ProtoReflect.Descriptor instead.
func (*GetKeyPointsByTourResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{14}
}

func (x *GetKeyPointsByTourResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tours_tours_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{15}
}

func (x *GetTourByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionSimulatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSimulatorRequest) Reset() {
	*x = PositionSimulatorRequest{}
	mi := &file_tours_tours_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSimulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSimulatorRequest) ProtoMessage() {}

func (x *PositionSimulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSimulatorRequest.ProtoReflect.Descriptor instead.
func (*PositionSimulatorRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{16}
}

func (x *PositionSimulatorRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_tours_tours_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePositionRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *UpdatePositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdatePositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PositionSimulatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSimulatorResponse) Reset() {
	*x = PositionSimulatorResponse{}
	mi := &file_tours_tours_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSimulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSimulatorResponse) ProtoMessage() {}

func (x *PositionSimulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSimulatorResponse.ProtoReflect.Descriptor instead.
func (*PositionSimulatorResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{18}
}

func (x *PositionSimulatorResponse) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *PositionSimulatorResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionSimulatorResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionSimulatorResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddTourDurationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TourId            int64                  `protobuf:"varint,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Transport         string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	DurationInMinutes int32                  `protobuf:"varint,3,opt,name=durationInMinutes,proto3" json:"durationInMinutes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddTourDurationRequest) Reset() {
	*x = AddTourDurationRequest{}
	mi := &file_tours_tours_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTourDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTourDurationRequest) ProtoMessage() {}

func (x *AddTourDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTourDurationRequest.ProtoReflect.Descriptor instead.
func (*AddTourDurationRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{19}
}

func (x *AddTourDurationRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *AddTourDurationRequest) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *AddTourDurationRequest) GetDurationInMinutes() int32 {
	if x != nil {
		return x.DurationInMinutes
	}
	return 0
}

type PublishTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        int64                  `protobuf:"varint,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_tours_tours_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{20}
}

func (x *PublishTourRequest) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

var File_tours_tours_proto protoreflect.FileDescriptor

const file_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x11tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x02\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"lengthInKm\x18\t \x01(\x01R\n" +
	"lengthInKm\x12$\n" +
	"\rpublishedTime\x18\n" +
	" \x01(\tR\rpublishedTime\x12 \n" +
	"\varchiveTime\x18\v \x01(\tR\varchiveTime\"\xa8\x02\n" +
	"\x0eAddTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06userId\x18\a \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"lengthInKm\x18\b \x01(\x01R\n" +
	"lengthInKm\x12$\n" +
	"\rpublishedTime\x18\t \x01(\tR\rpublishedTime\x12 \n" +
	"\varchiveTime\x18\n" +
	" \x01(\tR\varchiveTime\"/\n" +
	"\x15GetToursByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x16GetToursByUserResponse\x12!\n" +
	"\x05tours\x18\x01 \x03(\v2\v.tours.TourR\x05tours\"\xfe\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12 \n" +
	"\vimageBase64\x18\a \x01(\tR\vimageBase64\x12\x16\n" +
	"\x06tourId\x18\b \x01(\x03R\x06tourId\x12\"\n" +
	"\fpublicStatus\x18\t \x01(\x05R\fpublicStatus\"\xe2\x01\n" +
	"\x12AddKeyPointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vimageBase64\x18\x05 \x01(\tR\vimageBase64\x12\x16\n" +
	"\x06tourId\x18\x06 \x01(\x03R\x06tourId\x12\"\n" +
	"\fpublicStatus\x18\a \x01(\x05R\fpublicStatus\"'\n" +
	"\x15DeleteKeyPointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x16DeleteKeyPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x19GetKeyPointsByUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"K\n" +
	"\x1aGetKeyPointsByUserResponse\x12-\n" +
	"\tkeyPoints\x18\x01 \x03(\v2\x0f.tours.KeyPointR\tkeyPoints\"(\n" +
	"\x16GetKeyPointByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe0\x01\n" +
	"\x14AddTourReviewRequest\x12\x16\n" +
	"\x06idTour\x18\x01 \x01(\x03R\x06idTour\x12\x1c\n" +
	"\tidTourist\x18\x02 \x01(\x03R\tidTourist\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1a\n" +
	"\bdateTour\x18\x05 \x01(\tR\bdateTour\x12 \n" +
	"\vdateComment\x18\x06 \x01(\tR\vdateComment\x12\"\n" +
	"\fimagesBase64\x18\a \x03(\tR\fimagesBase64\"\xda\x01\n" +
	"\n" +
	"TourReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06idTour\x18\x02 \x01(\x03R\x06idTour\x12\x1c\n" +
	"\tidTourist\x18\x03 \x01(\x03R\tidTourist\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1a\n" +
	"\bdateTour\x18\x06 \x01(\tR\bdateTour\x12 \n" +
	"\vdateComment\x18\a \x01(\tR\vdateComment\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\"3\n" +
	"\x19GetKeyPointsByTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\x03R\x06tourId\"K\n" +
	"\x1aGetKeyPointsByTourResponse\x12-\n" +
	"\tkeyPoints\x18\x01 \x03(\v2\x0f.tours.KeyPointR\tkeyPoints\"$\n" +
	"\x12GetTourByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x18PositionSimulatorRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\"o\n" +
	"\x15UpdatePositionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\x91\x01\n" +
	"\x19PositionSimulatorResponse\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"|\n" +
	"\x16AddTourDurationRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\x03R\x06tourId\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12,\n" +
	"\x11durationInMinutes\x18\x03 \x01(\x05R\x11durationInMinutes\",\n" +
	"\x12PublishTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\x03R\x06tourId2\xdf\x03\n" +
	"\fToursService\x12D\n" +
	"\aAddTour\x12\x15.tours.AddTourRequest\x1a\v.tours.Tour\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/tours\x12o\n" +
	"\x0eGetToursByUser\x12\x1c.tours.GetToursByUserRequest\x1a\x1d.tours.GetToursByUserResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/tours/user/{userId}\x12M\n" +
	"\vGetTourById\x12\x19.tours.GetTourByIdRequest\x1a\v.tours.Tour\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/tour/{id}\x12h\n" +
	"\x0fAddTourDuration\x12\x1d.tours.AddTourDurationRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/tours/duration\x12_\n" +
	"\vPublishTour\x12\x19.tours.PublishTourRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/tours/publish2\x89\x05\n" +
	"\x0fKeyPointService\x12T\n" +
	"\vAddKeyPoint\x12\x19.tours.AddKeyPointRequest\x1a\x0f.tours.KeyPoint\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/keypoints\x12R\n" +
	"\x0eUpdateKeyPoint\x12\x0f.tours.KeyPoint\x1a\x0f.tours.KeyPoint\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/keypoints/{id}\x12j\n" +
	"\x0eDeleteKeyPoint\x12\x1c.tours.DeleteKeyPointRequest\x1a\x1d.tours.DeleteKeyPointResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/keypoints/{id}\x12\x7f\n" +
	"\x12GetKeyPointsByUser\x12 .tours.GetKeyPointsByUserRequest\x1a!.tours.GetKeyPointsByUserResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/keypoints/user/{userId}\x12^\n" +
	"\x0fGetKeyPointById\x12\x1d.tours.GetKeyPointByIdRequest\x1a\x0f.tours.KeyPoint\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/keypoints/{id}\x12\x7f\n" +
	"\x12GetKeyPointsByTour\x12 .tours.GetKeyPointsByTourRequest\x1a!.tours.GetKeyPointsByTourResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/keypoints/tour/{tourId}2r\n" +
	"\x11TourReviewService\x12]\n" +
	"\rAddTourReview\x12\x1b.tours.AddTourReviewRequest\x1a\x11.tours.TourReview\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/tour-reviews2\x96\x02\n" +
	"\x18PositionSimulatorService\x12}\n" +
	"\vGetPosition\x12\x1f.tours.PositionSimulatorRequest\x1a .tours.PositionSimulatorResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/position-simulator/{touristId}\x12{\n" +
	"\x0eUpdatePosition\x12\x1c.tours.UpdatePositionRequest\x1a .tours.PositionSimulatorResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/position-simulator/updateB&Z\vproto/tours\xaa\x02\x16GrpcServiceTranscodingb\x06proto3"

var (
	file_tours_tours_proto_rawDescOnce sync.Once
	file_tours_tours_proto_rawDescData []byte
)

func file_tours_tours_proto_rawDescGZIP() []byte {
	file_tours_tours_proto_rawDescOnce.Do(func() {
		file_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)))
	})
	return file_tours_tours_proto_rawDescData
}

var file_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tours_tours_proto_goTypes = []any{
	(*Tour)(nil),                       // 0: tours.Tour
	(*AddTourRequest)(nil),             // 1: tours.AddTourRequest
	(*GetToursByUserRequest)(nil),      // 2: tours.GetToursByUserRequest
	(*GetToursByUserResponse)(nil),     // 3: tours.GetToursByUserResponse
	(*KeyPoint)(nil),                   // 4: tours.KeyPoint
	(*AddKeyPointRequest)(nil),         // 5: tours.AddKeyPointRequest
	(*DeleteKeyPointRequest)(nil),      // 6: tours.DeleteKeyPointRequest
	(*DeleteKeyPointResponse)(nil),     // 7: tours.DeleteKeyPointResponse
	(*GetKeyPointsByUserRequest)(nil),  // 8: tours.GetKeyPointsByUserRequest
	(*GetKeyPointsByUserResponse)(nil), // 9: tours.GetKeyPointsByUserResponse
	(*GetKeyPointByIdRequest)(nil),     // 10: tours.GetKeyPointByIdRequest
	(*AddTourReviewRequest)(nil),       // 11: tours.AddTourReviewRequest
	(*TourReview)(nil),                 // 12: tours.TourReview
	(*GetKeyPointsByTourRequest)(nil),  // 13: tours.GetKeyPointsByTourRequest
	(*GetKeyPointsByTourResponse)(nil), // 14: tours.GetKeyPointsByTourResponse
	(*GetTourByIdRequest)(nil),         // 15: tours.GetTourByIdRequest
	(*PositionSimulatorRequest)(nil),   // 16: tours.PositionSimulatorRequest
	(*UpdatePositionRequest)(nil),      // 17: tours.UpdatePositionRequest
	(*PositionSimulatorResponse)(nil),  // 18: tours.PositionSimulatorResponse
	(*AddTourDurationRequest)(nil),     // 19: tours.AddTourDurationRequest
	(*PublishTourRequest)(nil),         // 20: tours.PublishTourRequest
	(*emptypb.Empty)(nil),              // 21: google.protobuf.Empty
}
var file_tours_tours_proto_depIdxs = []int32{
	0,  // 0: tours.GetToursByUserResponse.tours:type_name -> tours.Tour
	4,  // 1: tours.GetKeyPointsByUserResponse.keyPoints:type_name -> tours.KeyPoint
	4,  // 2: tours.GetKeyPointsByTourResponse.keyPoints:type_name -> tours.KeyPoint
	1,  // 3: tours.ToursService.AddTour:input_type -> tours.AddTourRequest
	2,  // 4: tours.ToursService.GetToursByUser:input_type -> tours.GetToursByUserRequest
	15, // 5: tours.ToursService.GetTourById:input_type -> tours.GetTourByIdRequest
	19, // 6: tours.ToursService.AddTourDuration:input_type -> tours.AddTourDurationRequest
	20, // 7: tours.ToursService.PublishTour:input_type -> tours.PublishTourRequest
	5,  // 8: tours.KeyPointService.AddKeyPoint:input_type -> tours.AddKeyPointRequest
	4,  // 9: tours.KeyPointService.UpdateKeyPoint:input_type -> tours.KeyPoint
	6,  // 10: tours.KeyPointService.DeleteKeyPoint:input_type -> tours.DeleteKeyPointRequest
	8,  // 11: tours.KeyPointService.GetKeyPointsByUser:input_type -> tours.GetKeyPointsByUserRequest
	10, // 12: tours.KeyPointService.GetKeyPointById:input_type -> tours.GetKeyPointByIdRequest
	13, // 13: tours.KeyPointService.GetKeyPointsByTour:input_type -> tours.GetKeyPointsByTourRequest
	11, // 14: tours.TourReviewService.AddTourReview:input_type -> tours.AddTourReviewRequest
	16, // 15: tours.PositionSimulatorService.GetPosition:input_type -> tours.PositionSimulatorRequest
	17, // 16: tours.PositionSimulatorService.UpdatePosition:input_type -> tours.UpdatePositionRequest
	0,  // 17: tours.ToursService.AddTour:output_type -> tours.Tour
	3,  // 18: tours.ToursService.GetToursByUser:output_type -> tours.GetToursByUserResponse
	0,  // 19: tours.ToursService.GetTourById:output_type -> tours.Tour
	21, // 20: tours.ToursService.AddTourDuration:output_type -> google.protobuf.Empty
	21, // 21: tours.ToursService.PublishTour:output_type -> google.protobuf.Empty
	4,  // 22: tours.KeyPointService.AddKeyPoint:output_type -> tours.KeyPoint
	4,  // 23: tours.KeyPointService.UpdateKeyPoint:output_type -> tours.KeyPoint
	7,  // 24: tours.KeyPointService.DeleteKeyPoint:output_type -> tours.DeleteKeyPointResponse
	9,  // 25: tours.KeyPointService.GetKeyPointsByUser:output_type -> tours.GetKeyPointsByUserResponse
	4,  // 26: tours.KeyPointService.GetKeyPointById:output_type -> tours.KeyPoint
	14, // 27: tours.KeyPointService.GetKeyPointsByTour:output_type -> tours.GetKeyPointsByTourResponse
	12, // 28: tours.TourReviewService.AddTourReview:output_type -> tours.TourReview
	18, // 29: tours.PositionSimulatorService.GetPosition:output_type -> tours.PositionSimulatorResponse
	18, // 30: tours.PositionSimulatorService.UpdatePosition:output_type -> tours.PositionSimulatorResponse
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tours_tours_proto_init() }
func file_tours_tours_proto_init() {
	if File_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_tours_tours_proto_goTypes,
		DependencyIndexes: file_tours_tours_proto_depIdxs,
		MessageInfos:      file_tours_tours_proto_msgTypes,
	}.Build()
	File_tours_tours_proto = out.File
	file_tours_tours_proto_goTypes = nil
	file_tours_tours_proto_depIdxs = nil
}
