// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: tours/tours.proto

package tours

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToursService_AddTour_FullMethodName        = "/tours.ToursService/AddTour"
	ToursService_GetToursByUser_FullMethodName = "/tours.ToursService/GetToursByUser"
)

// ToursServiceClient is the client API for ToursService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =================== Tours Service ===================
type ToursServiceClient interface {
	// Dodavanje ture
	AddTour(ctx context.Context, in *AddTourRequest, opts ...grpc.CallOption) (*Tour, error)
	GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetToursByUserResponse, error)
}

type toursServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToursServiceClient(cc grpc.ClientConnInterface) ToursServiceClient {
	return &toursServiceClient{cc}
}

func (c *toursServiceClient) AddTour(ctx context.Context, in *AddTourRequest, opts ...grpc.CallOption) (*Tour, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tour)
	err := c.cc.Invoke(ctx, ToursService_AddTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetToursByUser(ctx context.Context, in *GetToursByUserRequest, opts ...grpc.CallOption) (*GetToursByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToursByUserResponse)
	err := c.cc.Invoke(ctx, ToursService_GetToursByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToursServiceServer is the server API for ToursService service.
// All implementations must embed UnimplementedToursServiceServer
// for forward compatibility.
//
// =================== Tours Service ===================
type ToursServiceServer interface {
	// Dodavanje ture
	AddTour(context.Context, *AddTourRequest) (*Tour, error)
	GetToursByUser(context.Context, *GetToursByUserRequest) (*GetToursByUserResponse, error)
	mustEmbedUnimplementedToursServiceServer()
}

// UnimplementedToursServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToursServiceServer struct{}

func (UnimplementedToursServiceServer) AddTour(context.Context, *AddTourRequest) (*Tour, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTour not implemented")
}
func (UnimplementedToursServiceServer) GetToursByUser(context.Context, *GetToursByUserRequest) (*GetToursByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToursByUser not implemented")
}
func (UnimplementedToursServiceServer) mustEmbedUnimplementedToursServiceServer() {}
func (UnimplementedToursServiceServer) testEmbeddedByValue()                      {}

// UnsafeToursServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToursServiceServer will
// result in compilation errors.
type UnsafeToursServiceServer interface {
	mustEmbedUnimplementedToursServiceServer()
}

func RegisterToursServiceServer(s grpc.ServiceRegistrar, srv ToursServiceServer) {
	// If the following call pancis, it indicates UnimplementedToursServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToursService_ServiceDesc, srv)
}

func _ToursService_AddTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).AddTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_AddTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).AddTour(ctx, req.(*AddTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetToursByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetToursByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetToursByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetToursByUser(ctx, req.(*GetToursByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToursService_ServiceDesc is the grpc.ServiceDesc for ToursService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToursService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.ToursService",
	HandlerType: (*ToursServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTour",
			Handler:    _ToursService_AddTour_Handler,
		},
		{
			MethodName: "GetToursByUser",
			Handler:    _ToursService_GetToursByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}

const (
	KeyPointService_AddKeyPoint_FullMethodName        = "/tours.KeyPointService/AddKeyPoint"
	KeyPointService_UpdateKeyPoint_FullMethodName     = "/tours.KeyPointService/UpdateKeyPoint"
	KeyPointService_DeleteKeyPoint_FullMethodName     = "/tours.KeyPointService/DeleteKeyPoint"
	KeyPointService_GetKeyPointsByUser_FullMethodName = "/tours.KeyPointService/GetKeyPointsByUser"
	KeyPointService_GetKeyPointById_FullMethodName    = "/tours.KeyPointService/GetKeyPointById"
	KeyPointService_GetKeyPointsByTour_FullMethodName = "/tours.KeyPointService/GetKeyPointsByTour"
)

// KeyPointServiceClient is the client API for KeyPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =================== KeyPoint Service ===================
type KeyPointServiceClient interface {
	AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPoint, error)
	UpdateKeyPoint(ctx context.Context, in *KeyPoint, opts ...grpc.CallOption) (*KeyPoint, error)
	DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error)
	GetKeyPointsByUser(ctx context.Context, in *GetKeyPointsByUserRequest, opts ...grpc.CallOption) (*GetKeyPointsByUserResponse, error)
	GetKeyPointById(ctx context.Context, in *GetKeyPointByIdRequest, opts ...grpc.CallOption) (*KeyPoint, error)
	GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error)
}

type keyPointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyPointServiceClient(cc grpc.ClientConnInterface) KeyPointServiceClient {
	return &keyPointServiceClient{cc}
}

func (c *keyPointServiceClient) AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_AddKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) UpdateKeyPoint(ctx context.Context, in *KeyPoint, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_UpdateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyPointResponse)
	err := c.cc.Invoke(ctx, KeyPointService_DeleteKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointsByUser(ctx context.Context, in *GetKeyPointsByUserRequest, opts ...grpc.CallOption) (*GetKeyPointsByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsByUserResponse)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointById(ctx context.Context, in *GetKeyPointByIdRequest, opts ...grpc.CallOption) (*KeyPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPoint)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyPointServiceClient) GetKeyPointsByTour(ctx context.Context, in *GetKeyPointsByTourRequest, opts ...grpc.CallOption) (*GetKeyPointsByTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPointsByTourResponse)
	err := c.cc.Invoke(ctx, KeyPointService_GetKeyPointsByTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyPointServiceServer is the server API for KeyPointService service.
// All implementations must embed UnimplementedKeyPointServiceServer
// for forward compatibility.
//
// =================== KeyPoint Service ===================
type KeyPointServiceServer interface {
	AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPoint, error)
	UpdateKeyPoint(context.Context, *KeyPoint) (*KeyPoint, error)
	DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error)
	GetKeyPointsByUser(context.Context, *GetKeyPointsByUserRequest) (*GetKeyPointsByUserResponse, error)
	GetKeyPointById(context.Context, *GetKeyPointByIdRequest) (*KeyPoint, error)
	GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error)
	mustEmbedUnimplementedKeyPointServiceServer()
}

// UnimplementedKeyPointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyPointServiceServer struct{}

func (UnimplementedKeyPointServiceServer) AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) UpdateKeyPoint(context.Context, *KeyPoint) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyPoint not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointsByUser(context.Context, *GetKeyPointsByUserRequest) (*GetKeyPointsByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsByUser not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointById(context.Context, *GetKeyPointByIdRequest) (*KeyPoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointById not implemented")
}
func (UnimplementedKeyPointServiceServer) GetKeyPointsByTour(context.Context, *GetKeyPointsByTourRequest) (*GetKeyPointsByTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyPointsByTour not implemented")
}
func (UnimplementedKeyPointServiceServer) mustEmbedUnimplementedKeyPointServiceServer() {}
func (UnimplementedKeyPointServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyPointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyPointServiceServer will
// result in compilation errors.
type UnsafeKeyPointServiceServer interface {
	mustEmbedUnimplementedKeyPointServiceServer()
}

func RegisterKeyPointServiceServer(s grpc.ServiceRegistrar, srv KeyPointServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyPointService_ServiceDesc, srv)
}

func _KeyPointService_AddKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).AddKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_AddKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).AddKeyPoint(ctx, req.(*AddKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_UpdateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).UpdateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_UpdateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).UpdateKeyPoint(ctx, req.(*KeyPoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_DeleteKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).DeleteKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_DeleteKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).DeleteKeyPoint(ctx, req.(*DeleteKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointsByUser(ctx, req.(*GetKeyPointsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointById(ctx, req.(*GetKeyPointByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyPointService_GetKeyPointsByTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPointsByTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyPointServiceServer).GetKeyPointsByTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyPointService_GetKeyPointsByTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyPointServiceServer).GetKeyPointsByTour(ctx, req.(*GetKeyPointsByTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyPointService_ServiceDesc is the grpc.ServiceDesc for KeyPointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyPointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.KeyPointService",
	HandlerType: (*KeyPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddKeyPoint",
			Handler:    _KeyPointService_AddKeyPoint_Handler,
		},
		{
			MethodName: "UpdateKeyPoint",
			Handler:    _KeyPointService_UpdateKeyPoint_Handler,
		},
		{
			MethodName: "DeleteKeyPoint",
			Handler:    _KeyPointService_DeleteKeyPoint_Handler,
		},
		{
			MethodName: "GetKeyPointsByUser",
			Handler:    _KeyPointService_GetKeyPointsByUser_Handler,
		},
		{
			MethodName: "GetKeyPointById",
			Handler:    _KeyPointService_GetKeyPointById_Handler,
		},
		{
			MethodName: "GetKeyPointsByTour",
			Handler:    _KeyPointService_GetKeyPointsByTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}

const (
	TourReviewService_AddTourReview_FullMethodName = "/tours.TourReviewService/AddTourReview"
)

// TourReviewServiceClient is the client API for TourReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourReviewServiceClient interface {
	AddTourReview(ctx context.Context, in *AddTourReviewRequest, opts ...grpc.CallOption) (*TourReview, error)
}

type tourReviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourReviewServiceClient(cc grpc.ClientConnInterface) TourReviewServiceClient {
	return &tourReviewServiceClient{cc}
}

func (c *tourReviewServiceClient) AddTourReview(ctx context.Context, in *AddTourReviewRequest, opts ...grpc.CallOption) (*TourReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourReview)
	err := c.cc.Invoke(ctx, TourReviewService_AddTourReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourReviewServiceServer is the server API for TourReviewService service.
// All implementations must embed UnimplementedTourReviewServiceServer
// for forward compatibility.
type TourReviewServiceServer interface {
	AddTourReview(context.Context, *AddTourReviewRequest) (*TourReview, error)
	mustEmbedUnimplementedTourReviewServiceServer()
}

// UnimplementedTourReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourReviewServiceServer struct{}

func (UnimplementedTourReviewServiceServer) AddTourReview(context.Context, *AddTourReviewRequest) (*TourReview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTourReview not implemented")
}
func (UnimplementedTourReviewServiceServer) mustEmbedUnimplementedTourReviewServiceServer() {}
func (UnimplementedTourReviewServiceServer) testEmbeddedByValue()                           {}

// UnsafeTourReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourReviewServiceServer will
// result in compilation errors.
type UnsafeTourReviewServiceServer interface {
	mustEmbedUnimplementedTourReviewServiceServer()
}

func RegisterTourReviewServiceServer(s grpc.ServiceRegistrar, srv TourReviewServiceServer) {
	// If the following call pancis, it indicates UnimplementedTourReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourReviewService_ServiceDesc, srv)
}

func _TourReviewService_AddTourReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTourReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourReviewServiceServer).AddTourReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourReviewService_AddTourReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourReviewServiceServer).AddTourReview(ctx, req.(*AddTourReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourReviewService_ServiceDesc is the grpc.ServiceDesc for TourReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.TourReviewService",
	HandlerType: (*TourReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTourReview",
			Handler:    _TourReviewService_AddTourReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours.proto",
}
