// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blog/blog-service.proto

package blog

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogStatus int32

const (
	BlogStatus_DRAFT     BlogStatus = 0
	BlogStatus_PUBLISHED BlogStatus = 1
	BlogStatus_CLOSED    BlogStatus = 2
	BlogStatus_ACTIVE    BlogStatus = 3
	BlogStatus_FAMOUS    BlogStatus = 4
)

// Enum value maps for BlogStatus.
var (
	BlogStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "CLOSED",
		3: "ACTIVE",
		4: "FAMOUS",
	}
	BlogStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"CLOSED":    2,
		"ACTIVE":    3,
		"FAMOUS":    4,
	}
)

func (x BlogStatus) Enum() *BlogStatus {
	p := new(BlogStatus)
	*p = x
	return p
}

func (x BlogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_blog_service_proto_enumTypes[0].Descriptor()
}

func (BlogStatus) Type() protoreflect.EnumType {
	return &file_blog_blog_service_proto_enumTypes[0]
}

func (x BlogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlogStatus.Descriptor instead.
func (BlogStatus) EnumDescriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{0}
}

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Status        BlogStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=BlogStatus" json:"status,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RatingSum     int32                  `protobuf:"varint,8,opt,name=rating_sum,json=ratingSum,proto3" json:"rating_sum,omitempty"`
	Ratings       []*Rating              `protobuf:"bytes,9,rep,name=ratings,proto3" json:"ratings,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,10,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_blog_blog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Blog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Blog) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Blog) GetStatus() BlogStatus {
	if x != nil {
		return x.Status
	}
	return BlogStatus_DRAFT
}

func (x *Blog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Blog) GetRatingSum() int32 {
	if x != nil {
		return x.RatingSum
	}
	return 0
}

func (x *Blog) GetRatings() []*Rating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *Blog) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_blog_blog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{1}
}

func (x *Rating) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Rating) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Rating) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId        int64                  `protobuf:"varint,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_blog_blog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetBlogId() int64 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *Comment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Status        BlogStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=BlogStatus" json:"status,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBlogRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateBlogRequest) GetStatus() BlogStatus {
	if x != nil {
		return x.Status
	}
	return BlogStatus_DRAFT
}

func (x *CreateBlogRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type LikeBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        int64                  `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeBlogRequest) Reset() {
	*x = LikeBlogRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeBlogRequest) ProtoMessage() {}

func (x *LikeBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeBlogRequest.ProtoReflect.Descriptor instead.
func (*LikeBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{5}
}

func (x *LikeBlogRequest) GetBlogId() int64 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *LikeBlogRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeBlogResponse) Reset() {
	*x = LikeBlogResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeBlogResponse) ProtoMessage() {}

func (x *LikeBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeBlogResponse.ProtoReflect.Descriptor instead.
func (*LikeBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{6}
}

func (x *LikeBlogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        int64                  `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCommentRequest) GetBlogId() int64 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

func (x *CreateCommentRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogsRequest) Reset() {
	*x = GetBlogsRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsRequest) ProtoMessage() {}

func (x *GetBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{9}
}

type GetBlogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogsResponse) Reset() {
	*x = GetBlogsResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsResponse) ProtoMessage() {}

func (x *GetBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlogsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetBlogByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        int64                  `protobuf:"varint,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogByIdRequest) Reset() {
	*x = GetBlogByIdRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdRequest) ProtoMessage() {}

func (x *GetBlogByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBlogByIdRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlogByIdRequest) GetBlogId() int64 {
	if x != nil {
		return x.BlogId
	}
	return 0
}

type GetBlogByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogByIdResponse) Reset() {
	*x = GetBlogByIdResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdResponse) ProtoMessage() {}

func (x *GetBlogByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBlogByIdResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlogByIdResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

var File_blog_blog_service_proto protoreflect.FileDescriptor

const file_blog_blog_service_proto_rawDesc = "" +
	"\n" +
	"\x17blog/blog-service.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12#\n" +
	"\x06status\x18\x06 \x01(\x0e2\v.BlogStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"rating_sum\x18\b \x01(\x05R\tratingSum\x12!\n" +
	"\aratings\x18\t \x03(\v2\a.RatingR\aratings\x12$\n" +
	"\bcomments\x18\n" +
	" \x03(\v2\b.CommentR\bcomments\"r\n" +
	"\x06Rating\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x99\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\x03R\x06blogId\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa6\x01\n" +
	"\x11CreateBlogRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12#\n" +
	"\x06status\x18\x04 \x01(\x0e2\v.BlogStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"/\n" +
	"\x12CreateBlogResponse\x12\x19\n" +
	"\x04blog\x18\x01 \x01(\v2\x05.BlogR\x04blog\"C\n" +
	"\x0fLikeBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\x03R\x06blogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\",\n" +
	"\x10LikeBlogResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"[\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\x03R\x06blogId\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\";\n" +
	"\x15CreateCommentResponse\x12\"\n" +
	"\acomment\x18\x01 \x01(\v2\b.CommentR\acomment\"\x11\n" +
	"\x0fGetBlogsRequest\"/\n" +
	"\x10GetBlogsResponse\x12\x1b\n" +
	"\x05blogs\x18\x01 \x03(\v2\x05.BlogR\x05blogs\"-\n" +
	"\x12GetBlogByIdRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\x03R\x06blogId\"0\n" +
	"\x13GetBlogByIdResponse\x12\x19\n" +
	"\x04blog\x18\x01 \x01(\v2\x05.BlogR\x04blog*J\n" +
	"\n" +
	"BlogStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\n" +
	"\n" +
	"\x06FAMOUS\x10\x042\xa9\x03\n" +
	"\vBlogService\x12K\n" +
	"\n" +
	"CreateBlog\x12\x12.CreateBlogRequest\x1a\x13.CreateBlogResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/blog\x12H\n" +
	"\bLikeBlog\x12\x10.LikeBlogRequest\x1a\x05.Blog\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/blog/{blog_id}/like\x12g\n" +
	"\rCreateComment\x12\x15.CreateCommentRequest\x1a\x16.CreateCommentResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/blog/{blog_id}/comments\x12C\n" +
	"\bGetBlogs\x12\x10.GetBlogsRequest\x1a\x11.GetBlogsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/blogs\x12U\n" +
	"\vGetBlogById\x12\x13.GetBlogByIdRequest\x1a\x14.GetBlogByIdResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/blog/{blog_id}B\fZ\n" +
	"proto/blogb\x06proto3"

var (
	file_blog_blog_service_proto_rawDescOnce sync.Once
	file_blog_blog_service_proto_rawDescData []byte
)

func file_blog_blog_service_proto_rawDescGZIP() []byte {
	file_blog_blog_service_proto_rawDescOnce.Do(func() {
		file_blog_blog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_blog_service_proto_rawDesc), len(file_blog_blog_service_proto_rawDesc)))
	})
	return file_blog_blog_service_proto_rawDescData
}

var file_blog_blog_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blog_blog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_blog_blog_service_proto_goTypes = []any{
	(BlogStatus)(0),               // 0: BlogStatus
	(*Blog)(nil),                  // 1: Blog
	(*Rating)(nil),                // 2: Rating
	(*Comment)(nil),               // 3: Comment
	(*CreateBlogRequest)(nil),     // 4: CreateBlogRequest
	(*CreateBlogResponse)(nil),    // 5: CreateBlogResponse
	(*LikeBlogRequest)(nil),       // 6: LikeBlogRequest
	(*LikeBlogResponse)(nil),      // 7: LikeBlogResponse
	(*CreateCommentRequest)(nil),  // 8: CreateCommentRequest
	(*CreateCommentResponse)(nil), // 9: CreateCommentResponse
	(*GetBlogsRequest)(nil),       // 10: GetBlogsRequest
	(*GetBlogsResponse)(nil),      // 11: GetBlogsResponse
	(*GetBlogByIdRequest)(nil),    // 12: GetBlogByIdRequest
	(*GetBlogByIdResponse)(nil),   // 13: GetBlogByIdResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_blog_blog_service_proto_depIdxs = []int32{
	14, // 0: Blog.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: Blog.status:type_name -> BlogStatus
	2,  // 2: Blog.ratings:type_name -> Rating
	3,  // 3: Blog.comments:type_name -> Comment
	14, // 4: Rating.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: Comment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: CreateBlogRequest.status:type_name -> BlogStatus
	1,  // 7: CreateBlogResponse.blog:type_name -> Blog
	3,  // 8: CreateCommentResponse.comment:type_name -> Comment
	1,  // 9: GetBlogsResponse.blogs:type_name -> Blog
	1,  // 10: GetBlogByIdResponse.blog:type_name -> Blog
	4,  // 11: BlogService.CreateBlog:input_type -> CreateBlogRequest
	6,  // 12: BlogService.LikeBlog:input_type -> LikeBlogRequest
	8,  // 13: BlogService.CreateComment:input_type -> CreateCommentRequest
	10, // 14: BlogService.GetBlogs:input_type -> GetBlogsRequest
	12, // 15: BlogService.GetBlogById:input_type -> GetBlogByIdRequest
	5,  // 16: BlogService.CreateBlog:output_type -> CreateBlogResponse
	1,  // 17: BlogService.LikeBlog:output_type -> Blog
	9,  // 18: BlogService.CreateComment:output_type -> CreateCommentResponse
	11, // 19: BlogService.GetBlogs:output_type -> GetBlogsResponse
	13, // 20: BlogService.GetBlogById:output_type -> GetBlogByIdResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_blog_blog_service_proto_init() }
func file_blog_blog_service_proto_init() {
	if File_blog_blog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_blog_service_proto_rawDesc), len(file_blog_blog_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_blog_service_proto_goTypes,
		DependencyIndexes: file_blog_blog_service_proto_depIdxs,
		EnumInfos:         file_blog_blog_service_proto_enumTypes,
		MessageInfos:      file_blog_blog_service_proto_msgTypes,
	}.Build()
	File_blog_blog_service_proto = out.File
	file_blog_blog_service_proto_goTypes = nil
	file_blog_blog_service_proto_depIdxs = nil
}
