version: "3.7"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
       - monitoring

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - jaeger
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
       - ./grafana/dashboards:/etc/grafana/dashboards
       - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
       - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector endpoint
    networks:
       - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure
    ports:
      - "9099:9090"
    volumes:
       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml   # konfiguracija
       - prometheus-data:/prometheus 
    networks:
       - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
       - monitoring

  docker-stats-exporter:
    image: wywywywy/docker_stats_exporter
    container_name: docker-stats-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9487:9487"
    networks:
      - monitoring


networks:
  monitoring:
    name: monitoring

volumes:
  prometheus-data: