syntax = "proto3";
option go_package = "soa/follower/proto/stakeholders;stakeholders";


option csharp_namespace = "GrpcServiceTranscoding";

package stakeholders;
//package GrpcServiceTranscoding;

// The greeting service definition.
service StakeholdersService {
 // rpc Authorize (Credentials) returns (AuthenticationTokens) { }
	rpc Register (AccountRegistration) returns (User);
	rpc GetAllAccounts(PagedRequest) returns (AccountList);
	rpc Login (Credentials) returns (AuthenticationTokens);
	rpc BlockUser (BlockRequest) returns (Account);

}

// The request message containing the user's name.
message PagedRequest {
  int32 page = 1;
  int32 pageSize = 2;
}

message AccountList {
  repeated Account accounts = 1;
}

message Account {
  int64 id = 1;
  string username = 2;
  string email = 3;
  string role = 4;
  bool isActive = 5;
}

message AccountRegistration {
  string username = 1;
  string password = 2;
  string email = 3;
  string name = 4;
  string surname = 5;
  string profilePicture = 6;
  string biography = 7;
  string motto = 8;
  double wallet = 9;
  string imageBase64 = 10;
  string role = 11;
}

message User {
  int32 id = 1;
  string username = 2;
  bool isActive = 3;
}

message BlockRequest {
  int64 accountId = 1;
}

message Credentials {
  string username = 1;
  string password = 2;
}

message AuthenticationTokens {
  string accessToken = 1;
  string refreshToken = 2;
}



